server:
  servlet:
    contextPath: ${CONTEXT_PATH}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=${SERVER_TIMEZONE}&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  security:
#    user:
#      name: ${SECURITY_USER_NAME}
#      password: ${SECURITY_USER_PASSWORD}
