server:
  servlet:
    contextPath: ${CONTEXT_PATH}
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=${SERVER_TIMEZONE}&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
    show-sql: true
#  security:
#    user:
#      name: ${SECURITY_USER_NAME}
#      password: ${SECURITY_USER_PASSWORD}
